build(common): Upgrade minimal version of `tokio-stream` to v0.1.1
In CI, with a minimal versions lock file, we observed with

`cargo clippy --benches --examples --tests --no-deps --no-default-features -- -D warnings`

an error on `tokio-stream`:

error[E0432]: unresolved import `tokio_stream::wrappers`
  --> /home/luuk/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-test-0.4.2/src/io.rs:24:19
   |
24 | use tokio_stream::wrappers::UnboundedReceiverStream;
   |                   ^^^^^^^^ could not find `wrappers` in `tokio_stream`

Does `tokio-stream` v0.1 provide "wrappers" module? No.

The `wrappers` was [introduced in v0.1.1](https://github.com/tokio-rs/tokio/blob/master/tokio-stream/CHANGELOG.md#011-january-4-2021)

Lets upgrade to v0.1.1 and ship the updated Cargo.lock.